<script>
  import App from '../components/App.svelte';
</script>

<h1>Treemap of Greenhouse Gas Emissions by Country and Industrial Sector</h1>

<App />

<h3>Write-up: </h3>
<p> For our visualization, we decided to do a treemap to visualize greenhouse gas emissions for each country and grouped by industrial sector. Our data set was obtained from https://ourworldindata.org/emissions-by-sector. We decided to use a tree map to show the size of the greenhouse emissions for each country. For our data set, we had to use Pandas to reorganize our data so that it is in a hierarchal structure where the parent variable is 'year', with its child being 'industrial sector' and lastly 'country' being the child of that. Each country has a value for greenhouse emissions. The industrial sectors in the tree map are color coded with the size of each box correlating with the emissions by each country. For our interactive technique, used a slider to display the emission statistics for different years. We chose to use a slider due to year being a continuous variable and it is good for showing change over time. We considered using a drop down menu instead of a slider, however we thought having a slider would be a better option as it also allows us to switch between years easier in order to observe the changes. The boxes within the tree map adjust in size according to the changes in emission values. We also implemented a tool tip where you can see the labels for each country as well as their greenhouse emissions in the unit of million tons. We chose to have tool tips instead of having titles for each box as some boxes can be extremely small which causes the words to overlap with other boxes.</p>
<p> The development was split into different sections. We first spent some time discussing between us our initial concept as well as the details of our data for example, how would we structure the hiearchy so that it would make sense to be implemented in a tree map. The original data set was formatted as a csv file, this file has to be converted in a hierarchal structure and saved as a json file. All team members participated in reformatting the original data set, Manat's version was used in the end. Additionally, Manat was responsible for creating a skeleton tree map which worked for one year which took around 3 hours. Haotian created a working slider for the tree map which changed the size of the boxes depending on the year, and Ammie worked on the visualization of the slider, write up as well as the final check which took around 2 hours. </p>
